### PR TITLE
Bring back support for original "end" keyword

### PR DESCRIPTION
**Pull request by kappa**
It was removed in 2016 in https://github.com/freeduke33/rerap2/commit/a837886c0751aa7707a1d89f198654f2e9e82e5e#diff-bde656ac968c9f22b7168e822d3b1071a173b926b173d6b45bde8db93ff2a9e4L134 -- probably by mistake.

### CODE REVIEW

**Comment by freeduke33** [comment]
It was made by purpose - there was no English equivalient for this token. Could you please suggest something to fix it? Using simply "end" is unfortunately not a case because it's already used as T_END token.

**Comment by kappa** [comment]
What do you think about "done"? Pretty close meaning to "всё".

**Comment by freeduke33** [comment]
Ok, please prepare your patch with this token.

**Comment by freeduke33** [comment]
Unfortunately, you missed the distinct statement DO..OD as in example/fibonacci.rap.
May be it's better to split fix and improvement into different PRs?

**Pull request merged**
